services:
  app:
    container_name: maps-app
    build:
      context: .
      dockerfile: Dockerfile
    image: maps-app
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    container_name: maps_v2
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maps_v2
    volumes:
      - ./db-dump/:/var/lib/postgresql/data
#      - init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  maps_postgres-data:
    driver: local